In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
df = pd.read_csv("/content/drive/My Drive/student.csv")

In [6]:
df = df.rename(columns={"mark": "score"})
print(df)

    id         name  class  score  gender passed
0    1     John Deo   Four     75  female   pass
1    2     Max Ruin  Three     85    male   pass
2    3       Arnold  Three     55    male   fail
3    4   Krish Star   Four     60  female   pass
4    5    John Mike   Four     60  female   pass
5    6    Alex John   Four     55    male   fail
6    7  My John Rob  Fifth     78    male   pass
7    8       Asruid   Five     85    male   pass
8    9      Tes Qry    Six     78     NaN   pass
9   10     Big John   Four     55  female   fail
10  11       Ronald    Six     89  female   pass
11  12        Recky    Six     94  female   pass
12  13          Kty  Seven     88  female   pass
13  14         Bigy  Seven     88  female   pass
14  15     Tade Row    NaN     88    male   pass
15  16        Gimmy   Four     88    male   pass
16  17        Tumyu    Six     54    male   fail
17  18        Honny   Five     75    male   pass
18  19        Tinny   Nine     18    male   fail
19  20       Jackly   Nine     65  female   pass
20  21   Babby John   Four     69  female   pass
21  22       Reggid  Seven     55  female   fail
22  23        Herod  Eight     79    male   pass
23  24    Tiddy Now  Seven     78    male   pass
24  25     Giff Tow  Seven     88    male   pass
25  26       Crelea  Seven     79    male   pass
26  27          NaN  Three     81     NaN   pass
27  28    Rojj Base  Seven     86  female   pass
28  29  Tess Played  Seven     55    male   fail
29  30    Reppy Red    Six     79  female   pass
30  31  Marry Toeey   Four     88    male   pass
31  32    Binn Rott  Seven     90  female   pass
32  33    Kenn Rein    Six     96  female   pass
33  34     Gain Toe  Seven     69    male   pass
34  35   Rows Noump    Six     88  female   pass

In [7]:
df = df.drop(columns=["passed"])
print(df)

    id         name  class  score  gender
0    1     John Deo   Four     75  female
1    2     Max Ruin  Three     85    male
2    3       Arnold  Three     55    male
3    4   Krish Star   Four     60  female
4    5    John Mike   Four     60  female
5    6    Alex John   Four     55    male
6    7  My John Rob  Fifth     78    male
7    8       Asruid   Five     85    male
8    9      Tes Qry    Six     78     NaN
9   10     Big John   Four     55  female
10  11       Ronald    Six     89  female
11  12        Recky    Six     94  female
12  13          Kty  Seven     88  female
13  14         Bigy  Seven     88  female
14  15     Tade Row    NaN     88    male
15  16        Gimmy   Four     88    male
16  17        Tumyu    Six     54    male
17  18        Honny   Five     75    male
18  19        Tinny   Nine     18    male
19  20       Jackly   Nine     65  female
20  21   Babby John   Four     69  female
21  22       Reggid  Seven     55  female
22  23        Herod  Eight     79    male
23  24    Tiddy Now  Seven     78    male
24  25     Giff Tow  Seven     88    male
25  26       Crelea  Seven     79    male
26  27          NaN  Three     81     NaN
27  28    Rojj Base  Seven     86  female
28  29  Tess Played  Seven     55    male
29  30    Reppy Red    Six     79  female
30  31  Marry Toeey   Four     88    male
31  32    Binn Rott  Seven     90  female
32  33    Kenn Rein    Six     96  female
33  34     Gain Toe  Seven     69    male
34  35   Rows Noump    Six     88  female

In [4]:
print(df[df["class"]=="Four"])

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [15]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/student.csv")

df = df.rename(columns={"mark": "score"})

df["grade"] = ["A" if x >= 86 else ("B" if x >= 70 else ("C" if x >= 60 else "D")) for x in df["score"]]
print(df)

    id         name  class  score  gender grade
0    1     John Deo   Four     75  female     B
1    2     Max Ruin  Three     85    male     B
2    3       Arnold  Three     55    male     D
3    4   Krish Star   Four     60  female     C
4    5    John Mike   Four     60  female     C
5    6    Alex John   Four     55    male     D
6    7  My John Rob  Fifth     78    male     B
7    8       Asruid   Five     85    male     B
8    9      Tes Qry    Six     78     NaN     B
9   10     Big John   Four     55  female     D
10  11       Ronald    Six     89  female     A
11  12        Recky    Six     94  female     A
12  13          Kty  Seven     88  female     A
13  14         Bigy  Seven     88  female     A
14  15     Tade Row    NaN     88    male     A
15  16        Gimmy   Four     88    male     A
16  17        Tumyu    Six     54    male     D
17  18        Honny   Five     75    male     B
18  19        Tinny   Nine     18    male     D
19  20       Jackly   Nine     65  female     C
20  21   Babby John   Four     69  female     C
21  22       Reggid  Seven     55  female     D
22  23        Herod  Eight     79    male     B
23  24    Tiddy Now  Seven     78    male     B
24  25     Giff Tow  Seven     88    male     A
25  26       Crelea  Seven     79    male     B
26  27          NaN  Three     81     NaN     B
27  28    Rojj Base  Seven     86  female     A
28  29  Tess Played  Seven     55    male     D
29  30    Reppy Red    Six     79  female     B
30  31  Marry Toeey   Four     88    male     A
31  32    Binn Rott  Seven     90  female     A
32  33    Kenn Rein    Six     96  female     A
33  34     Gain Toe  Seven     69    male     C
34  35   Rows Noump    Six     88  female     A

In [14]:
x = df.sort_values(by="score", ascending=False)
print(x)

    id         name  class  score  gender grade
32  33    Kenn Rein    Six     96  female     A
11  12        Recky    Six     94  female     A
31  32    Binn Rott  Seven     90  female     A
10  11       Ronald    Six     89  female     A
30  31  Marry Toeey   Four     88    male     A
34  35   Rows Noump    Six     88  female     A
24  25     Giff Tow  Seven     88    male     A
14  15     Tade Row    NaN     88    male     A
15  16        Gimmy   Four     88    male     A
12  13          Kty  Seven     88  female     A
13  14         Bigy  Seven     88  female     A
27  28    Rojj Base  Seven     86  female     A
7    8       Asruid   Five     85    male     B
1    2     Max Ruin  Three     85    male     B
26  27          NaN  Three     81     NaN     B
29  30    Reppy Red    Six     79  female     B
25  26       Crelea  Seven     79    male     B
22  23        Herod  Eight     79    male     B
6    7  My John Rob  Fifth     78    male     B
23  24    Tiddy Now  Seven     78    male     B
8    9      Tes Qry    Six     78     NaN     B
17  18        Honny   Five     75    male     B
0    1     John Deo   Four     75  female     B
33  34     Gain Toe  Seven     69    male     C
20  21   Babby John   Four     69  female     C
19  20       Jackly   Nine     65  female     C
3    4   Krish Star   Four     60  female     C
4    5    John Mike   Four     60  female     C
2    3       Arnold  Three     55    male     D
5    6    Alex John   Four     55    male     D
9   10     Big John   Four     55  female     D
21  22       Reggid  Seven     55  female     D
28  29  Tess Played  Seven     55    male     D
16  17        Tumyu    Six     54    male     D
18  19        Tinny   Nine     18    male     D

In [ ]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
x = df[["name", "mark"]]
print(x)

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
display(df.head(5))

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female